GT: true
SR: true
T_max: 1000
base_dir: .
batch_size: 64
clip: 10
config: ./savedata/1/GATraj//config_train.yaml
dataset: eth5
eta_min: 3.0e-06
final_mode: 20
gpu: 0
hidden_size: 64
ifGaussian: false
ifshow_detail: true
ifvalid: true
input_mix: false
input_offset: true
input_position: false
input_size: 2
learning_rate: 0.0001
load_model: 0
lr_step: 20
min_obs: 8
mlp_decoder: false
model: models.GATraj
model_dir: ./savedata/1/GATraj/
neighbor_thred: 10
num_epochs: 1000
num_pred: 1
obs_length: 8
output_size: 2
pass_time: 2
phase: train
pred_length: 12
randomRotate: true
ratio: 0.95
save_base_dir: ./savedata/
save_dir: ./savedata/1/
seq_length: 20
show_step: 40
step_ratio: 0.5
test_set: 1
train_model: GATraj
using_cuda: true
val_fraction: 0
x_encoder_head: 8
x_encoder_layers: 3
z_dim: 32
